- themes/bb-theme/class-bb-theme-compat.php
> respect the bb-theme settings for setting no header and no footer

- admin/class-bb-admin-ui.php
- admin/render-admin-panel.php
> support BB's page templates for selecting header and footer

- bb-header-footer.php
- class-bb-header-footer.php
> Check current theme by function names/class names and constants

- class-bb-header-footer.php
This reverts commit d0a6b4d831d016f656deedf21bee616ad5405bb8.
> Revert "allow header and footer ids to be filtered"

- class-bb-header-footer.php
> Calling shortcode function directly

- README.md
- assets/css/bb-header-footer.css
- class-bb-header-footer.php
- readme.txt
- themes/wp-primer-theme/primer-theme-compat.php
> Support for primer theme

- assets/css/bb-header-footer.css
> improve the shrink header effect

- README.md
- readme.txt
> add link to the plugins GitHub repo in the readme

- assets/css/bb-header-footer.css
> Fix: shrink header breaking the aspect ratio in the image module

- README.md
- bb-header-footer.php
- class-bb-header-footer.php
- languages/bb-header-footer.pot
- readme.txt
Translation for v1.1.5 release
> Updated the change log, Tested upto tag, Version number

- README.md
- admin/class-bb-admin-ui.php
- admin/render-admin-panel.php
- bb-header-footer.php
- class-bb-header-footer.php
- readme.txt
- themes/astra/class-astra-compat.php
- themes/bb-theme/class-bb-theme-compat.php
- themes/generatepress/class-generatepress-compat.php
- themes/genesis/class-genesis-compat.php
- themes/wp-primer-theme/class-bhf-primer-theme-compat.php
so that the settings can be filtered from the child theme.
#53
> delay running hooks until action 'wp'

- README.md
- bb-header-footer.php
- class-bb-header-footer.php
- package.json
- readme.txt
- Fix: Load CSS/JS of Header and Footer in <header> fixing flash of unstyled content. - Fixes #73
> Version 1.1.8

- README.md
- readme.txt
- Updated Tested Upto tag in readme file
> Updated Tested Upto tag in readme file

- README.md
- bb-header-footer.php
- class-bb-header-footer.php
- readme.txt
Changed **insert_layout** function to **render_content_by_id** to fix the layout issue in the header/footer
> Fix: Layout CSS/JS not rendering in some cases

- README.md
- readme.txt
> WordPress 5.5 Compatibility

- README.md
- readme.txt
> WordPress 5.6 compatibility

- README.md
- readme.txt
- WordPress 5.7 update compatibility
> WordPress 5.7 update compatibility

- README.md
- bb-header-footer.php
- readme.txt
###Description
Updated stable tag to 1.2.2
> updated stable tag 

- README.md
- readme.txt
No issues were found
Updated tested up to tag to 6.0
> WordPress 6.0 compatibility

- README.md
- readme.txt
No issues were found
Updated Tested up to tag to 6.2
> WordPress 6.2 compatibility

- README.md
- package-lock.json
- readme.txt
> WordPress 6.3 compatibility

- README.md
- readme.txt
This pull request includes minor updates to the documentation files to reflect the latest tested version of the software.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L6-R6): Updated the "Tested up to" version from 6.6 to 6.7.
* [`readme.txt`](diffhunk://#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6L6-R6): Updated the "Tested up to" version from 6.6 to 6.7.
> EPS-814: Wordpress 6.7 compatibility

- README.md
- readme.txt
Try it out on a free dummy site - https://zipwp.org/plugins/bb-header-footer
> Updated Demo Link in readme file

- README.md
- readme.txt
Try the live demo of [PRODUCT_NAME]
> Updated - Product name dummy link
